//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Clients = new HashSet<Client>();
            this.Parents = new HashSet<Parent>();
        }
    
        public int AddressID { get; set; }
        public int BuildingNumber { get; set; }
        public string StreetName { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public int ZipCode { get; set; }
        public int AdditionalNumbers { get; set; }
    
        public virtual ICollection<Client> Clients { get; set; }
        public virtual ICollection<Parent> Parents { get; set; }
    }
}
