//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment_View
    {
        public string RoomNumber { get; set; }
        public string Student_FName { get; set; }
        public string Stuent_LName { get; set; }
        public string Client_FName { get; set; }
        public string Client_LName { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public string Repeat { get; set; }
        public string Note { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public string MiddleName { get; set; }
        public string Expr1 { get; set; }
        public int UserID { get; set; }
        public int ClientID { get; set; }
    }
}
