//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Information
    {
        public Client_Information()
        {
            this.Healths = new HashSet<Health>();
            this.Food_Allergy = new HashSet<Food_Allergy>();
            this.Immunizations = new HashSet<Immunization>();
            this.Motor_Development = new HashSet<Motor_Development>();
        }
    
        public int ClientInformationID { get; set; }
        public string FileNumber { get; set; }
        public string DifficultyDescription { get; set; }
        public System.DateTime CompletionDate { get; set; }
        public string AdditionalInformation { get; set; }
        public int ClientID { get; set; }
        public int HearingID { get; set; }
        public int SchoolID { get; set; }
        public int SocialID { get; set; }
        public int BirthID { get; set; }
        public int SpeechLanguageID { get; set; }
        public string Ethincity { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string ClientLanguage { get; set; }
        public string LanguageAtHome { get; set; }
        public string PrimaryPhysician { get; set; }
        public string PhysicianAddress { get; set; }
        public string PhysicianPhone { get; set; }
        public string ReferrerName { get; set; }
        public string ReferrerPhone { get; set; }
        public string EmergencyContactName { get; set; }
        public string EmergencyContactRelationship { get; set; }
        public string EmergencyContactPhone { get; set; }
        public string QuestionnaireFillerName { get; set; }
        public string QuestionnaireFillerRelationship { get; set; }
        public string OtherSiblings { get; set; }
        public string SiblingSLPProblems { get; set; }
        public string SiblingAcademicDifficulties { get; set; }
        public string OtherPregnancies { get; set; }
    
        public virtual Birth Birth { get; set; }
        public virtual Child Child { get; set; }
        public virtual Client Client { get; set; }
        public virtual Hearing Hearing { get; set; }
        public virtual School School { get; set; }
        public virtual Social Social { get; set; }
        public virtual Speech_Language Speech_Language { get; set; }
        public virtual ICollection<Health> Healths { get; set; }
        public virtual ICollection<Food_Allergy> Food_Allergy { get; set; }
        public virtual ICollection<Immunization> Immunizations { get; set; }
        public virtual ICollection<Motor_Development> Motor_Development { get; set; }
        public virtual Marital_Status Marital_Status { get; set; }
    }
}
