//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_View
    {
        public string Client_FName { get; set; }
        public string Client_MName { get; set; }
        public string Client_LName { get; set; }
        public string Client_Email { get; set; }
        public string Mobile { get; set; }
        public string FileNumber { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public System.DateTime CompletionDate { get; set; }
        public int StudentID { get; set; }
        public string Student_FName { get; set; }
        public string Student_LName { get; set; }
        public string Parent_FName { get; set; }
        public string Parent_LName { get; set; }
        public string Parent_Mobile { get; set; }
        public string Parent_Email { get; set; }
        public string MiddleName { get; set; }
    }
}
