//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SLHSClinicEntities : DbContext
    {
        public SLHSClinicEntities()
            : base("name=SLHSClinicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Address> Addresses { get; set; }
        public DbSet<Adult> Adults { get; set; }
        public DbSet<Appointment> Appointments { get; set; }
        public DbSet<Assessment_Objective> Assessment_Objective { get; set; }
        public DbSet<Assessment_Proposal> Assessment_Proposal { get; set; }
        public DbSet<Authentication> Authentications { get; set; }
        public DbSet<Behavior> Behaviors { get; set; }
        public DbSet<Birth> Births { get; set; }
        public DbSet<Child> Children { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<Client_Information> Client_Information { get; set; }
        public DbSet<Clinical_Goals> Clinical_Goals { get; set; }
        public DbSet<Communication> Communications { get; set; }
        public DbSet<Diagnosi> Diagnosis { get; set; }
        public DbSet<Fluency> Fluencies { get; set; }
        public DbSet<Fluharty> Fluharties { get; set; }
        public DbSet<Food_Allergy> Food_Allergy { get; set; }
        public DbSet<Health> Healths { get; set; }
        public DbSet<Hearing> Hearings { get; set; }
        public DbSet<Immunization> Immunizations { get; set; }
        public DbSet<Jaw> Jaws { get; set; }
        public DbSet<Language_Notes> Language_Notes { get; set; }
        public DbSet<Lip> Lips { get; set; }
        public DbSet<Motor_Development> Motor_Development { get; set; }
        public DbSet<Parent> Parents { get; set; }
        public DbSet<Personality> Personalities { get; set; }
        public DbSet<Pharynx_Tonsil> Pharynx_Tonsil { get; set; }
        public DbSet<Plan> Plans { get; set; }
        public DbSet<Repeated_Grade> Repeated_Grade { get; set; }
        public DbSet<Resource> Resources { get; set; }
        public DbSet<Resource_Request> Resource_Request { get; set; }
        public DbSet<Room> Rooms { get; set; }
        public DbSet<School> Schools { get; set; }
        public DbSet<Screening_SOAP_Note> Screening_SOAP_Note { get; set; }
        public DbSet<Section> Sections { get; set; }
        public DbSet<Session> Sessions { get; set; }
        public DbSet<Session_Feedback> Session_Feedback { get; set; }
        public DbSet<SOAP_Note> SOAP_Note { get; set; }
        public DbSet<SOAP_Objective> SOAP_Objective { get; set; }
        public DbSet<Social> Socials { get; set; }
        public DbSet<Special_Classroom> Special_Classroom { get; set; }
        public DbSet<Speech_Language> Speech_Language { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<Supervisor> Supervisors { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Teacher_Assistant> Teacher_Assistant { get; set; }
        public DbSet<Tongue> Tongues { get; set; }
        public DbSet<Treatment_Plan> Treatment_Plan { get; set; }
        public DbSet<Treatment_Progress> Treatment_Progress { get; set; }
        public DbSet<Voice> Voices { get; set; }
        public DbSet<Appointment_View> Appointment_View { get; set; }
        public DbSet<Client_View> Client_View { get; set; }
        public DbSet<Request_View> Request_View { get; set; }
        public DbSet<Session_View> Session_View { get; set; }
        public DbSet<Student_View> Student_View { get; set; }
    }
}
