//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinical_Goals
    {
        public int ClinicalGoalsID { get; set; }
        public string LongTermGoals { get; set; }
        public string ShortTermGoals { get; set; }
    }
}
