//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Communication
    {
        public int CommunicationID { get; set; }
        public string Method { get; set; }
        public int SpeechLanguageID { get; set; }
    
        public virtual Speech_Language Speech_Language { get; set; }
    }
}
