//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS
{
    using System;
    using NewSLHS.DAL;
    using System.Collections.Generic;
    
    public partial class Diagnosis
    {
        public Diagnosis()
        {
            this.Client_Information = new HashSet<Client_Information>();
        }
    
        public int DiagnosisID { get; set; }
        public Nullable<int> CleftPlatal { get; set; }
        public Nullable<int> CerebalPalsy { get; set; }
        public Nullable<int> MentalRetardation { get; set; }
        public Nullable<int> BrainDysfunction { get; set; }
        public Nullable<int> DownSyndrome { get; set; }
        public Nullable<int> DefectsNoseThroatEars { get; set; }
        public string Other { get; set; }
    
        public virtual ICollection<Client_Information> Client_Information { get; set; }
    }
}
