//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosi
    {
        public int DiagnosisID { get; set; }
        public Nullable<int> CleftPlatal { get; set; }
        public Nullable<int> CerebalPalsy { get; set; }
        public Nullable<int> MentalRetardation { get; set; }
        public Nullable<int> BrainDysfunction { get; set; }
        public Nullable<int> DownSyndrome { get; set; }
        public Nullable<int> DefectsNoseThroatEars { get; set; }
        public string Other { get; set; }
    }
}
