//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fluency
    {
        public Fluency()
        {
            this.Screening_SOAP_Note = new HashSet<Screening_SOAP_Note>();
        }
    
        public int FluencyID { get; set; }
        public string Fluency1 { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Repetition { get; set; }
        public Nullable<int> Blocks { get; set; }
        public Nullable<int> Prolongations { get; set; }
        public Nullable<int> SecondaryBehavior { get; set; }
    
        public virtual ICollection<Screening_SOAP_Note> Screening_SOAP_Note { get; set; }
    }
}
