//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Immunization
    {
        public int ImmunizationID { get; set; }
        public int ImmunizationName { get; set; }
        public string Other { get; set; }
        public int ClientInformationID { get; set; }
    
        public virtual Client_Information Client_Information { get; set; }
    }
}
