//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language_Notes
    {
        public Language_Notes()
        {
            this.Fluharties = new HashSet<Fluharty>();
        }
    
        public int LanguageNotesID { get; set; }
        public string Language { get; set; }
        public decimal MLRVocabulary { get; set; }
        public decimal MLRSentence { get; set; }
        public string LanguageConcern { get; set; }
        public decimal CELFRawScore { get; set; }
        public decimal CELFCriterionScore { get; set; }
        public string Comments { get; set; }
        public int ScreeningSOAPNoteID { get; set; }
    
        public virtual ICollection<Fluharty> Fluharties { get; set; }
        public virtual Screening_SOAP_Note Screening_SOAP_Note { get; set; }
    }
}
