//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lip
    {
        public Lip()
        {
            this.Screening_SOAP_Note = new HashSet<Screening_SOAP_Note>();
        }
    
        public int LipsID { get; set; }
        public Nullable<int> Pucker { get; set; }
        public Nullable<int> Retraction { get; set; }
        public Nullable<int> IntaOralPressure { get; set; }
        public Nullable<int> Strength { get; set; }
    
        public virtual ICollection<Screening_SOAP_Note> Screening_SOAP_Note { get; set; }
    }
}
