//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marital_Status
    {
        public Marital_Status()
        {
            this.Client_Information = new HashSet<Client_Information>();
        }
    
        public int MaritalStatusID { get; set; }
        public string MartialStatus { get; set; }
    
        public virtual ICollection<Client_Information> Client_Information { get; set; }
    }
}
