//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motor_Development
    {
        public int MotorDevelopmentID { get; set; }
        public int BalanceLoss { get; set; }
        public int CuttingDifficulty { get; set; }
        public int ColoringDifficulty { get; set; }
        public int HoldingUtensilsDifficulty { get; set; }
        public int ClientInformationID { get; set; }
        public string Other { get; set; }
        public string OtherInformation { get; set; }
        public Nullable<int> OptionID { get; set; }
    
        public virtual Client_Information Client_Information { get; set; }
        public virtual Yes_No Yes_No { get; set; }
    }
}
