//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent
    {
        public Parent()
        {
            this.Clients = new HashSet<Client>();
        }
    
        public int ParentID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Education { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string HomePhone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Occupation { get; set; }
        public string WorkLocation { get; set; }
        public int Relation { get; set; }
        public int MaritalStatus { get; set; }
        public int AddressID { get; set; }
        public string WorkPhone { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Client> Clients { get; set; }
    }
}
