//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        public Plan()
        {
            this.Screening_SOAP_Note = new HashSet<Screening_SOAP_Note>();
        }
    
        public int PlanID { get; set; }
        public string OtherRecommendations { get; set; }
        public Nullable<int> FollowUp { get; set; }
        public Nullable<int> PassedHearingScreeing { get; set; }
        public string HearingEvaluation { get; set; }
        public Nullable<int> RescreenHearing { get; set; }
        public Nullable<int> PassedSlScreeing { get; set; }
        public Nullable<int> SLEvaluation { get; set; }
        public string RescreenSL { get; set; }
    
        public virtual ICollection<Screening_SOAP_Note> Screening_SOAP_Note { get; set; }
    }
}
