//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repeated_Grade
    {
        public int RepeatedGradeID { get; set; }
        public string RepeatedGrade { get; set; }
        public string RepeatedGradeReason { get; set; }
        public int SchoolID { get; set; }
    
        public virtual School School { get; set; }
    }
}
