//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public Resource()
        {
            this.Resource_Request = new HashSet<Resource_Request>();
        }
    
        public int ResourceID { get; set; }
        public string Name { get; set; }
        public string SerialNumber { get; set; }
        public int Quantity { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<Resource_Request> Resource_Request { get; set; }
    }
}
