//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public School()
        {
            this.Client_Information = new HashSet<Client_Information>();
            this.Repeated_Grade = new HashSet<Repeated_Grade>();
            this.Special_Classroom = new HashSet<Special_Classroom>();
        }
    
        public int SchoolID { get; set; }
        public string SchoolCollege { get; set; }
        public int AnyRepeatedGrades { get; set; }
        public string RepeatedGradeReason { get; set; }
        public Nullable<int> SpecialClassroom { get; set; }
        public string ProgressNotes { get; set; }
    
        public virtual ICollection<Client_Information> Client_Information { get; set; }
        public virtual ICollection<Repeated_Grade> Repeated_Grade { get; set; }
        public virtual ICollection<Special_Classroom> Special_Classroom { get; set; }
    }
}
