//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screening_SOAP_Note
    {
        public Screening_SOAP_Note()
        {
            this.Language_Notes = new HashSet<Language_Notes>();
        }
    
        public int SessionID { get; set; }
        public string Subjective { get; set; }
        public string Hearing { get; set; }
        public string Reliability { get; set; }
        public string Articulation { get; set; }
        public string Errors { get; set; }
        public string Substitution { get; set; }
        public string Omission { get; set; }
        public string Distortion { get; set; }
        public string SpeechIntelligibility { get; set; }
        public string OralMechanism { get; set; }
        public Nullable<int> TogueID { get; set; }
        public Nullable<int> PharynxID { get; set; }
        public Nullable<int> LipsID { get; set; }
        public Nullable<int> JawsID { get; set; }
        public int PlanID { get; set; }
        public int VoiceID { get; set; }
        public int FluencyID { get; set; }
        public Nullable<int> DAHProtocol { get; set; }
        public Nullable<int> FluhartyTest { get; set; }
        public Nullable<int> Test5 { get; set; }
        public Nullable<int> OralScreen { get; set; }
        public Nullable<int> VocalScreen { get; set; }
        public Nullable<int> FluencyScreen { get; set; }
    
        public virtual Fluency Fluency { get; set; }
        public virtual Jaw Jaw { get; set; }
        public virtual ICollection<Language_Notes> Language_Notes { get; set; }
        public virtual Lip Lip { get; set; }
        public virtual Pharynx_Tonsil Pharynx_Tonsil { get; set; }
        public virtual Plan Plan { get; set; }
        public virtual Session Session { get; set; }
        public virtual Tongue Tongue { get; set; }
        public virtual Voice Voice { get; set; }
    }
}
