//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public Section()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int SectionID { get; set; }
        public int Number { get; set; }
        public string CourseCode { get; set; }
        public string Semester { get; set; }
        public string AcademicYear { get; set; }
        public int SupervisorID { get; set; }
        public int TAID { get; set; }
    
        public virtual Supervisor Supervisor { get; set; }
        public virtual Teacher_Assistant Teacher_Assistant { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
