//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session_View
    {
        public string Client_FName { get; set; }
        public string Client_LName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public System.DateTime SessionDate { get; set; }
        public string Supervisor_FName { get; set; }
        public string Supervisor_Lname { get; set; }
        public string Student_FName { get; set; }
        public string Student_LName { get; set; }
        public string ReferrerName { get; set; }
        public string RoomNumber { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public decimal EvaluationScore { get; set; }
    }
}
