//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session_Feedback
    {
        public int FeedbackID { get; set; }
        public int ClinicianOnTime { get; set; }
        public int LessonPlan { get; set; }
        public int UsingPreviousNotes { get; set; }
        public int MaterialsPreparation { get; set; }
        public int UsingTallySheet { get; set; }
        public int SeatingAppropriateness { get; set; }
        public int UsingReports { get; set; }
        public int RapportBuilding { get; set; }
        public int ProfessionalAttitude { get; set; }
        public int ClientManagement { get; set; }
        public int StimuliAppropriate { get; set; }
        public int EnvitonmentOrganization { get; set; }
        public int Reinforcement { get; set; }
        public int FlexibleGoalsRevising { get; set; }
        public int UsingStratiegies { get; set; }
        public int InstructionsClearness { get; set; }
        public int CounselingParents { get; set; }
        public int SOAPSubmission { get; set; }
        public int CarryoverAssignments { get; set; }
        public int SuggestionsImplementation { get; set; }
        public string Comments { get; set; }
        public int SessionID { get; set; }
    
        public virtual Session Session { get; set; }
    }
}
