//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOAP_Objective
    {
        public int ObjectiveID { get; set; }
        public string ObjectiveDescription { get; set; }
        public string ObjectiveProcedure { get; set; }
        public string Assessment { get; set; }
        public int SOAPNoteID { get; set; }
    
        public virtual SOAP_Note SOAP_Note { get; set; }
    }
}
