//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOAP_Note
    {
        public SOAP_Note()
        {
            this.SOAP_Objective = new HashSet<SOAP_Objective>();
        }
    
        public int SessionID { get; set; }
        public string Subjective { get; set; }
        public string SOAPNotePlan { get; set; }
        public string Materials { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual ICollection<SOAP_Objective> SOAP_Objective { get; set; }
    }
}
