//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Special_Classroom
    {
        public int SpecialClassroomID { get; set; }
        public string Attachment { get; set; }
        public string Description { get; set; }
        public int SchoolID { get; set; }
    
        public virtual School School { get; set; }
    }
}
