//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speech_Language
    {
        public Speech_Language()
        {
            this.Client_Information = new HashSet<Client_Information>();
            this.Communications = new HashSet<Communication>();
        }
    
        public int SpeechLanguageID { get; set; }
        public string SpeechComparedToSiblings { get; set; }
        public int ThinkingOfWordsDifficulty { get; set; }
        public int UnderstandingSpeechDifficulty { get; set; }
        public int FollowingDirectionsDifficulty { get; set; }
        public int AttentionDuringWatchingTv { get; set; }
        public int AttentionDuringReading { get; set; }
        public int LookingAtPicturesAttention { get; set; }
        public int ListeningToStoryAttention { get; set; }
        public int AttentionDuringPlaying { get; set; }
        public string BetterCommunicationEfforts { get; set; }
        public Nullable<int> Gestures { get; set; }
        public Nullable<int> NonSpeechNoises { get; set; }
        public Nullable<int> SingleWords { get; set; }
        public Nullable<int> Sentences { get; set; }
    
        public virtual ICollection<Client_Information> Client_Information { get; set; }
        public virtual ICollection<Communication> Communications { get; set; }
    }
}
