//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Resource_Request = new HashSet<Resource_Request>();
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int UserID { get; set; }
        public int StudentID { get; set; }
        public int SectionID { get; set; }
        public int SupervisorID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public int Status { get; set; }
        public int AuthenticationID { get; set; }
    
        public virtual Authentication Authentication { get; set; }
        public virtual ICollection<Resource_Request> Resource_Request { get; set; }
        public virtual Section Section { get; set; }
        public virtual Supervisor Supervisor { get; set; }
        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}
