//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_View
    {
        public int StudentID { get; set; }
        public string Student_FName { get; set; }
        public string Student_LName { get; set; }
        public int Section { get; set; }
        public string Supervisor_LName { get; set; }
        public string Supervisor_FName { get; set; }
        public string TA_OfficeNo { get; set; }
        public string TA_FName { get; set; }
        public string TA_LName { get; set; }
        public string TA_Email { get; set; }
        public string Supervisor_Email { get; set; }
        public string OfficeNumber { get; set; }
    }
}
