//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher_Assistant
    {
        public Teacher_Assistant()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Resource_Request = new HashSet<Resource_Request>();
            this.Sections = new HashSet<Section>();
        }
    
        public int UserID { get; set; }
        public int EmployeeID { get; set; }
        public string OfficeNumber { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public int Status { get; set; }
        public int AuthenticationID { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual Authentication Authentication { get; set; }
        public virtual ICollection<Resource_Request> Resource_Request { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
    }
}
