//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tongue
    {
        public Tongue()
        {
            this.Screening_SOAP_Note = new HashSet<Screening_SOAP_Note>();
        }
    
        public int TongueID { get; set; }
        public int Protrusion { get; set; }
        public int Lateralization { get; set; }
        public int Elevation { get; set; }
        public int Depression { get; set; }
        public int Strength { get; set; }
    
        public virtual ICollection<Screening_SOAP_Note> Screening_SOAP_Note { get; set; }
    }
}
