//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment_Progress
    {
        public int SessionID { get; set; }
        public int ScheduledVisitsNumber { get; set; }
        public string TreatmentResults { get; set; }
        public string Recommendations { get; set; }
        public string LongTermGoals { get; set; }
        public string ShortTermGoals { get; set; }
        public string InitialConcern { get; set; }
        public string ScreeningEvaluationInformation { get; set; }
        public string TestingResults { get; set; }
        public string Diagnosis { get; set; }
        public string RecentEvaluationResults { get; set; }
        public string RecommendedTreatmentFrequency { get; set; }
    
        public virtual Session Session { get; set; }
    }
}
