//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voice
    {
        public Voice()
        {
            this.Screening_SOAP_Note = new HashSet<Screening_SOAP_Note>();
        }
    
        public int VoiceID { get; set; }
        public string Voice1 { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Quality { get; set; }
        public Nullable<int> Pitch { get; set; }
        public Nullable<int> Intensity { get; set; }
        public Nullable<int> Resonance { get; set; }
    
        public virtual ICollection<Screening_SOAP_Note> Screening_SOAP_Note { get; set; }
    }
}
