//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSLHS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yes_No
    {
        public Yes_No()
        {
            this.Socials = new HashSet<Social>();
            this.Motor_Development = new HashSet<Motor_Development>();
        }
    
        public int OptionID { get; set; }
        public string Option { get; set; }
    
        public virtual ICollection<Social> Socials { get; set; }
        public virtual ICollection<Motor_Development> Motor_Development { get; set; }
    }
}
